---
name: Build and Validation
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fjwillemsen/setup-nox2@v3.0.0
      - run: nox
